Repository CS2103JAN2018-T15-B4/main, pull requests merged in 2018-04, with the labels that each got.

#93 UI and ExportCommand Improvements
  README.adoc
  collated/functional/dezhanglee.md
  collated/functional/x3tsunayh.md
  collated/test/dezhanglee.md
  collated/test/x3tsunayh.md
  docs/AboutUs.adoc
  docs/ContactUs.adoc
  docs/diagrams/ExportSequenceDiagram.pptx
  docs/images/Ui.png
  src/main/java/seedu/address/commons/exceptions/InvalidFileException.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/CsvFileStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAddressBookStorage.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.high, type.story, type.task

#99 SwitchTabCommand Functionality
  README.adoc
  docs/AboutUs.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/SwitchTabCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/FindEventCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/model/EventBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.medium, type.enhancement, type.task

#112 Find Command: able to find by name and tag
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/tag/TagContainsKeywordsPredicate.java
  src/test/data/XmlSerializableAddressBookTest/typicalAddressBook.xml
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high, type.enhancement

#124 Google Search Command Implementation + Debugging
  data/addressbook.xml
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/GoogleContactNameEvent.java
  src/main/java/seedu/address/logic/commands/GoogleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/GoogleCommandParser.java
  src/main/java/seedu/address/ui/AnchorPaneNode.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/CalendarView.java
  src/main/java/seedu/address/ui/LinkedInWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/chrome_icon.png
  src/main/resources/images/linkedin_icon.png
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/CalendarView.fxml
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/LinkedInWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: priority.medium, type.enhancement, type.task

#135 Update find command: Find by phone and by address
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/TagContainsKeywordsPredicateTest.java
Labels: priority.high, status.readytomerge, type.story

#150 StatusBarFooter Bug Fix
  collated/functional/CYX28.md
  collated/functional/x3tsunayh.md
  collated/test/CYX28.md
  collated/test/dezhanglee.md
  collated/test/jill858.md
  collated/test/x3tsunayh.md
  data/addressbook.xml
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/AddEventCommandSequenceDiagram.pptx
  docs/diagrams/DeleteEventCommandSequenceDiagram.pptx
  docs/diagrams/EditEventCommandSequenceDiagram.pptx
  docs/diagrams/ExportCommandSequenceDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/AddEventCommandSequenceDiagram.png
  docs/images/DeleteEventCommandSequenceDiagram.png
  docs/images/EditEventCommandSequenceDiagram.png
  docs/images/ExportCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SwitchTab.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/SortEventCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlEventBookStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableEventBook.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/guitests/guihandles/EventCardHandle.java
  src/test/java/guitests/guihandles/EventListPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/AddEventCommandTest.java
  src/test/java/seedu/address/storage/XmlEventBookStorageTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalEventBook.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
Labels: severity.low, type.bug

#152 Command: Update Convert Currency to include API
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ConvertCommand.java
  src/main/java/seedu/address/model/Currency.java
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/ConvertCommandTest.java
  src/test/java/seedu/address/model/CurrencyTest.java
Labels: priority.medium, type.enhancement

#158 Bug fix
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/GoogleCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.bug
